# Generated by Django 4.2.7 on 2024-08-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_listings',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='total_listings',
            field=models.IntegerField(default=0),
        ),
    ]
