# Generated by Django 4.2.7 on 2024-08-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_last_login_token_user_current_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_session_id',
        ),
        migrations.AddField(
            model_name='user',
            name='current_login_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
