# Generated by Django 4.2.7 on 2024-08-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_current_login_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_jwt_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
