# Generated by Django 4.2.7 on 2024-09-10 16:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
