# Generated by Django 4.2.7 on 2024-09-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_useractionlog_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='session_id',
            field=models.UUIDField(editable=False),
        ),
    ]
